### ISSUE TITLE
postgresql을 연결할때는 

### ISSUE THREAD

**Issue by tommyjr1** [dsc-sookmyung/2022-G.Ipsa-SolutionChallenge#8]
로컬에 디비 설치했고 테스트용으로 usertable만든다음에
라우터로 디비에 쿼리 보내라구 해서 /todos쓰면 대답 받게 했는데
그냥 /todos 페이지가 없다고나와서 돌아버리겟는중임니다,,

혹시 아시는분,,
찾아보니까 postgres 연결할때 typeorm도 쓸 수 있다던데 이거 많이 쓰는건가요,, 지금 pool 쓰는걸로 하고있는데 다시 해봐야하나해서,,
내일까지 뒤집어볼게 미안해ㅠㅠㅠ,,

**Comment by JYBESiU** [comment]
우리 회사도 typeORM 쓰던데!
에러는 모르겠습니다.....

**Comment by tommyjr1** [comment]
> 우리 회사도 typeORM 쓰던데! 에러는 모르겠습니다.....

와!!!! 와아아!!!! 됐다!!!!! 와!!!!!!!!!!!!
